In [3]:
import numpy as np
import pandas as pd

## Exercice 1

In [10]:
N = 15*12
K = 100e6
swaprate = 1.1/100

In [11]:
LIBOR = np.array([-54.9, -54.7, -56.2, -60.1])/10000

In [12]:
swaprate_q = (1+swaprate)**(1/4) - 1
swaprate_q

0.002738728493097309

In [13]:
LIBOR_q = (1+LIBOR)**(1/4) - 1
LIBOR_q

array([-0.00137533, -0.00137031, -0.00140797, -0.0015059 ])

In [19]:
dtmp = pd.DataFrame([LIBOR_q * K, np.full(4,swaprate_q*K)]).T
dtmp.index = ['Q1','Q2','Q3','Q4']
dtmp.columns = ['jambe variable', 'jambe fixe']
dtmp

jambe variable    jambe fixe
Q1  -137533.471776  273872.84931
Q2  -137031.406873  273872.84931
Q3  -140797.078243  273872.84931
Q4  -150589.818031  273872.84931

In [15]:
dtmp = pd.DataFrame(LIBOR_q * K - swaprate_q*K)
dtmp.index = ['Q1','Q2','Q3','Q4']
dtmp.columns = ['Gain ou perte']
dtmp

Gain ou perte
Q1 -411406.321086
Q2 -410904.256183
Q3 -414669.927553
Q4 -424462.667341

## Exercice 2

In [23]:
CDS = np.array([107.5, 108.8, 114.5, 109])/10000
LGD = 45/100

In [24]:
PD = 1- np.exp(-CDS/LGD)
PD

array([0.02360581, 0.02388784, 0.02512346, 0.02393122])

In [10]:
dtmp = pd.DataFrame(np.round(PD*100,4))
dtmp.index = ['Q1','Q2','Q3','Q4']
dtmp.columns = ['PD 1 an (en %)']
dtmp

PD 1 an (en %)
Q1          2.3606
Q2          2.3888
Q3          2.5123
Q4          2.3931

In [11]:
PD = 1- np.exp(-CDS/LGD*np.tile(np.arange(1,10+1),(4,1)).T)
PD

array([[0.02360581, 0.02388784, 0.02512346, 0.02393122],
       [0.04665438, 0.04720504, 0.04961574, 0.04728973],
       [0.06915888, 0.06996526, 0.07349268, 0.07008925],
       [0.09113213, 0.09218177, 0.09676975, 0.09234315],
       [0.11258669, 0.11386759, 0.11946202, 0.11406448],
       [0.1335348 , 0.13503537, 0.14158419, 0.135266  ],
       [0.15398841, 0.15569751, 0.16315056, 0.15596014],
       [0.1739592 , 0.17586607, 0.18417512, 0.17615904],
       [0.19345856, 0.19555284, 0.20467147, 0.19587456],
       [0.21249762, 0.21476935, 0.22465287, 0.21511826]])

In [12]:
dtmp = pd.DataFrame(np.round(PD.T*100,4))
dtmp.index = ['Q1','Q2','Q3','Q4']
dtmp

0       1       2       3        4        5        6        7  \
Q1  2.3606  4.6654  6.9159  9.1132  11.2587  13.3535  15.3988  17.3959   
Q2  2.3888  4.7205  6.9965  9.2182  11.3868  13.5035  15.5698  17.5866   
Q3  2.5123  4.9616  7.3493  9.6770  11.9462  14.1584  16.3151  18.4175   
Q4  2.3931  4.7290  7.0089  9.2343  11.4064  13.5266  15.5960  17.6159   

          8        9  
Q1  19.3459  21.2498  
Q2  19.5553  21.4769  
Q3  20.4671  22.4653  
Q4  19.5875  21.5118

## Exercice 3

In [13]:
PD = np.array([2.5,2.8,2.9,4.9])/100
LGD = 45/100

In [14]:
CDS = -np.log(1-PD)*LGD
CDS*100*100

array([113.93013593, 127.79763535, 132.42964811, 226.08547397])

In [15]:
dtmp = pd.DataFrame(np.round(CDS*100*100,2))
dtmp.index = ['Q1','Q2','Q3','Q4']
dtmp.columns = ['CDS (en bps)']
dtmp

CDS (en bps)
Q1        113.93
Q2        127.80
Q3        132.43
Q4        226.09

In [16]:
-np.log(np.random.uniform(0,1,10)) / (CDS[-1]/LGD)

array([21.47467807, 54.21217304, 19.75161348, 18.97166562,  0.21641386,
        7.32542089, 18.61161215,  1.81531529, 13.08225949, 27.82773532])

In [29]:
np.random.exponential(1/(CDS[-1]/LGD),10)

array([46.07885744,  5.87806537,  2.05531078, 13.56098997, 58.62165492,
       49.59580075, 43.33832645,  2.07681868,  0.89901898,  1.72929789])

In [34]:
L_fix = 50e6 * np.full(10*4,0)
L_var = 50e6 * np.full(10*4,0)

default_time = np.random.exponential(1/(CDS[-1]/LGD),1)

for t in range(40):
    if default_time < t/4:
        L_var[t] = 50e6 * LGD
        break
    L_fix[t] = 50e6 * 0.028

print(default_time)
print(L_fix/1e6)
print(L_var/1e6)

[8.06186283]
[1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4
 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 0.  0.  0.
 0.  0.  0.  0. ]
[ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.  22.5  0.   0.   0.   0.   0.   0. ]
